apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: ZIPKIN_URL
          value: "{{ .Values.env.ZIPKIN_URL }}"
        - name: JWT_SECRET
          value: "{{ .Values.env.JWT_SECRET }}"
        - name: USERS_API_ADDRESS
          value: "{{ .Values.env.USERS_API_ADDRESS }}"
        - name: AUTH_API_PORT
          value: "{{ .Values.env.AUTH_API_PORT }}"