replicaCount: 1
image:
  repository: ventana1901/auth-api
  tag: v1
  pullPolicy: IfNotPresent

env:
  ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
  JWT_SECRET: "PRFT"
  USERS_API_ADDRESS: "http://users-api:8083"
  AUTH_API_PORT: "8000"